version: '3.9'

services:

  db:
    image: 'postgres:latest'
    container_name: techcenter-postgres-database
    restart: always
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: techcenter
      POSTGRES_PASSWORD: techcenter
      POSTGRES_DB: techcenter
   
    networks:
      - techcenter

  adminer:
    image: 'adminer:latest'
    restart: always
    ports:
      - 8080:8080

    networks:
      - techcenter

    links:
      - db

networks:
  techcenter: {}